# Generated by Django 4.1.13 on 2024-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=555, verbose_name='Malumot'),
        ),
    ]
