# Generated by Django 4.1.13 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='instagramm',
            field=models.CharField(max_length=55),
        ),
    ]
